name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test
      
      - name: Rename mochawesome report
        run: mv cypress/reports/mochawesome.html cypress/reports/meu-relatorio-final.html

      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: cypress/reports/relatorio-final-testes.html