name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Ensure Cypress binary has execution permissions
        run: chmod +x ./node_modules/.bin/cypress

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run Cypress tests
        run: npm run test

      - name: Verify report file exists
        run: ls -l ./reports/

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Relatório dos testes
          path: ./reports/
